//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOF.Web.Application.WebApp.Private.Gestion {
    
    
    public partial class GesCalendario {
        
        /// <summary>
        /// wucFullCalendar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GOF.Web.Include.WebUserControls.FullCalendar.wucFullCalendar wucFullCalendar1;
    }
}
